# Generated by Django 2.0.2 on 2018-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date of job'),
        ),
    ]
