# Generated by Django 2.0.2 on 2018-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180520_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='copy',
            field=models.TextField(null=True, verbose_name='copy'),
        ),
    ]
