# Generated by Django 2.0.2 on 2018-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='entry title')),
                ('date', models.DateField(verbose_name='entry timestamp')),
                ('image', models.ImageField(upload_to='img/blogs', verbose_name='entry thumbnail')),
                ('summary', models.TextField(verbose_name='entry body')),
            ],
        ),
    ]
